server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://rm-uf6914e21vv948nikyo.mysql.rds.aliyuncs.com/pet-find?useUnicode=true&characterEncoding=utf-8
    username: pet_find_admin
    password: 19180319zZJ
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 200MB
      max-request-size: 200MB
      resolve-lazily: false

  redis:
    # 主机位置
    host: r-uf6eadbd897d91e4pd.redis.rds.aliyuncs.com
    # 主机端口号
    port: 6379
    # redis数据库密码
    password: 19180319zZJ
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 2000

    # 最大空闲数
    maxIdle: 10
    #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    maxActive: 10
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxTotal: 10
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
    minEvictableIdleTimeMillis: 300000
    #每次释放连接的最大数目,默认3
    numTestsPerEvictionRun: 1024

    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: false
    #在空闲时检查有效性, 默认false
    testWhileIdle: false
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    timeBetweenEvictionRunsMillis: 30000



# 整合Mybatis
mybatis:
  # ** 表示在mapper下不管有多少文件夹，都可以全部识别
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: petfind.pojo
  #  打印sql相关的日志信息
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
